//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lere333
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мебель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мебель()
        {
            this.Оформление = new HashSet<Оформление>();
        }
    
        public int Артикул { get; set; }
        public Nullable<int> Склад { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Склад Склад1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оформление> Оформление { get; set; }
    }
}
